// Code generated by ent, DO NOT EDIT.

package usersadmin

import (
	"gojeksrepo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldName, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldPassword, v))
}

// StatusAdmin applies equality check predicate on the "status_admin" field. It's identical to StatusAdminEQ.
func StatusAdmin(v int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldStatusAdmin, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldContainsFold(FieldName, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldContainsFold(FieldPassword, v))
}

// StatusAdminEQ applies the EQ predicate on the "status_admin" field.
func StatusAdminEQ(v int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldEQ(FieldStatusAdmin, v))
}

// StatusAdminNEQ applies the NEQ predicate on the "status_admin" field.
func StatusAdminNEQ(v int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNEQ(FieldStatusAdmin, v))
}

// StatusAdminIn applies the In predicate on the "status_admin" field.
func StatusAdminIn(vs ...int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldIn(FieldStatusAdmin, vs...))
}

// StatusAdminNotIn applies the NotIn predicate on the "status_admin" field.
func StatusAdminNotIn(vs ...int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldNotIn(FieldStatusAdmin, vs...))
}

// StatusAdminGT applies the GT predicate on the "status_admin" field.
func StatusAdminGT(v int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGT(FieldStatusAdmin, v))
}

// StatusAdminGTE applies the GTE predicate on the "status_admin" field.
func StatusAdminGTE(v int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldGTE(FieldStatusAdmin, v))
}

// StatusAdminLT applies the LT predicate on the "status_admin" field.
func StatusAdminLT(v int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLT(FieldStatusAdmin, v))
}

// StatusAdminLTE applies the LTE predicate on the "status_admin" field.
func StatusAdminLTE(v int) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.FieldLTE(FieldStatusAdmin, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsersAdmin) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsersAdmin) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsersAdmin) predicate.UsersAdmin {
	return predicate.UsersAdmin(sql.NotPredicates(p))
}
