// Code generated by ent, DO NOT EDIT.

package triprating

import (
	"gojeksrepo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldLTE(FieldID, id))
}

// TripID applies equality check predicate on the "trip_id" field. It's identical to TripIDEQ.
func TripID(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldTripID, v))
}

// FromUserID applies equality check predicate on the "from_user_id" field. It's identical to FromUserIDEQ.
func FromUserID(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldFromUserID, v))
}

// ToUserID applies equality check predicate on the "to_user_id" field. It's identical to ToUserIDEQ.
func ToUserID(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldToUserID, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v int) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldRating, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldComment, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldCreatedAt, v))
}

// TripIDEQ applies the EQ predicate on the "trip_id" field.
func TripIDEQ(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldTripID, v))
}

// TripIDNEQ applies the NEQ predicate on the "trip_id" field.
func TripIDNEQ(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldNEQ(FieldTripID, v))
}

// TripIDIn applies the In predicate on the "trip_id" field.
func TripIDIn(vs ...uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldIn(FieldTripID, vs...))
}

// TripIDNotIn applies the NotIn predicate on the "trip_id" field.
func TripIDNotIn(vs ...uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldNotIn(FieldTripID, vs...))
}

// FromUserIDEQ applies the EQ predicate on the "from_user_id" field.
func FromUserIDEQ(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldFromUserID, v))
}

// FromUserIDNEQ applies the NEQ predicate on the "from_user_id" field.
func FromUserIDNEQ(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldNEQ(FieldFromUserID, v))
}

// FromUserIDIn applies the In predicate on the "from_user_id" field.
func FromUserIDIn(vs ...uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldIn(FieldFromUserID, vs...))
}

// FromUserIDNotIn applies the NotIn predicate on the "from_user_id" field.
func FromUserIDNotIn(vs ...uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldNotIn(FieldFromUserID, vs...))
}

// ToUserIDEQ applies the EQ predicate on the "to_user_id" field.
func ToUserIDEQ(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldToUserID, v))
}

// ToUserIDNEQ applies the NEQ predicate on the "to_user_id" field.
func ToUserIDNEQ(v uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldNEQ(FieldToUserID, v))
}

// ToUserIDIn applies the In predicate on the "to_user_id" field.
func ToUserIDIn(vs ...uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldIn(FieldToUserID, vs...))
}

// ToUserIDNotIn applies the NotIn predicate on the "to_user_id" field.
func ToUserIDNotIn(vs ...uuid.UUID) predicate.TripRating {
	return predicate.TripRating(sql.FieldNotIn(FieldToUserID, vs...))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v int) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v int) predicate.TripRating {
	return predicate.TripRating(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...int) predicate.TripRating {
	return predicate.TripRating(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...int) predicate.TripRating {
	return predicate.TripRating(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v int) predicate.TripRating {
	return predicate.TripRating(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v int) predicate.TripRating {
	return predicate.TripRating(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v int) predicate.TripRating {
	return predicate.TripRating(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v int) predicate.TripRating {
	return predicate.TripRating(sql.FieldLTE(FieldRating, v))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.TripRating {
	return predicate.TripRating(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.TripRating {
	return predicate.TripRating(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldHasSuffix(FieldComment, v))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.TripRating {
	return predicate.TripRating(sql.FieldContainsFold(FieldComment, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TripRating {
	return predicate.TripRating(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTrip applies the HasEdge predicate on the "trip" edge.
func HasTrip() predicate.TripRating {
	return predicate.TripRating(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TripTable, TripColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTripWith applies the HasEdge predicate on the "trip" edge with a given conditions (other predicates).
func HasTripWith(preds ...predicate.Trip) predicate.TripRating {
	return predicate.TripRating(func(s *sql.Selector) {
		step := newTripStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFromUser applies the HasEdge predicate on the "from_user" edge.
func HasFromUser() predicate.TripRating {
	return predicate.TripRating(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FromUserTable, FromUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromUserWith applies the HasEdge predicate on the "from_user" edge with a given conditions (other predicates).
func HasFromUserWith(preds ...predicate.User) predicate.TripRating {
	return predicate.TripRating(func(s *sql.Selector) {
		step := newFromUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasToUser applies the HasEdge predicate on the "to_user" edge.
func HasToUser() predicate.TripRating {
	return predicate.TripRating(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ToUserTable, ToUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasToUserWith applies the HasEdge predicate on the "to_user" edge with a given conditions (other predicates).
func HasToUserWith(preds ...predicate.User) predicate.TripRating {
	return predicate.TripRating(func(s *sql.Selector) {
		step := newToUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TripRating) predicate.TripRating {
	return predicate.TripRating(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TripRating) predicate.TripRating {
	return predicate.TripRating(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TripRating) predicate.TripRating {
	return predicate.TripRating(sql.NotPredicates(p))
}
