// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gojeksrepo/ent/predicate"
	"gojeksrepo/ent/trip"
	"gojeksrepo/ent/triprating"
	"gojeksrepo/ent/user"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TripRatingQuery is the builder for querying TripRating entities.
type TripRatingQuery struct {
	config
	ctx          *QueryContext
	order        []triprating.OrderOption
	inters       []Interceptor
	predicates   []predicate.TripRating
	withTrip     *TripQuery
	withFromUser *UserQuery
	withToUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TripRatingQuery builder.
func (trq *TripRatingQuery) Where(ps ...predicate.TripRating) *TripRatingQuery {
	trq.predicates = append(trq.predicates, ps...)
	return trq
}

// Limit the number of records to be returned by this query.
func (trq *TripRatingQuery) Limit(limit int) *TripRatingQuery {
	trq.ctx.Limit = &limit
	return trq
}

// Offset to start from.
func (trq *TripRatingQuery) Offset(offset int) *TripRatingQuery {
	trq.ctx.Offset = &offset
	return trq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (trq *TripRatingQuery) Unique(unique bool) *TripRatingQuery {
	trq.ctx.Unique = &unique
	return trq
}

// Order specifies how the records should be ordered.
func (trq *TripRatingQuery) Order(o ...triprating.OrderOption) *TripRatingQuery {
	trq.order = append(trq.order, o...)
	return trq
}

// QueryTrip chains the current query on the "trip" edge.
func (trq *TripRatingQuery) QueryTrip() *TripQuery {
	query := (&TripClient{config: trq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := trq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := trq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(triprating.Table, triprating.FieldID, selector),
			sqlgraph.To(trip.Table, trip.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, triprating.TripTable, triprating.TripColumn),
		)
		fromU = sqlgraph.SetNeighbors(trq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFromUser chains the current query on the "from_user" edge.
func (trq *TripRatingQuery) QueryFromUser() *UserQuery {
	query := (&UserClient{config: trq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := trq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := trq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(triprating.Table, triprating.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, triprating.FromUserTable, triprating.FromUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(trq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryToUser chains the current query on the "to_user" edge.
func (trq *TripRatingQuery) QueryToUser() *UserQuery {
	query := (&UserClient{config: trq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := trq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := trq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(triprating.Table, triprating.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, triprating.ToUserTable, triprating.ToUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(trq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TripRating entity from the query.
// Returns a *NotFoundError when no TripRating was found.
func (trq *TripRatingQuery) First(ctx context.Context) (*TripRating, error) {
	nodes, err := trq.Limit(1).All(setContextOp(ctx, trq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{triprating.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (trq *TripRatingQuery) FirstX(ctx context.Context) *TripRating {
	node, err := trq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TripRating ID from the query.
// Returns a *NotFoundError when no TripRating ID was found.
func (trq *TripRatingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = trq.Limit(1).IDs(setContextOp(ctx, trq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{triprating.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (trq *TripRatingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := trq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TripRating entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TripRating entity is found.
// Returns a *NotFoundError when no TripRating entities are found.
func (trq *TripRatingQuery) Only(ctx context.Context) (*TripRating, error) {
	nodes, err := trq.Limit(2).All(setContextOp(ctx, trq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{triprating.Label}
	default:
		return nil, &NotSingularError{triprating.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (trq *TripRatingQuery) OnlyX(ctx context.Context) *TripRating {
	node, err := trq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TripRating ID in the query.
// Returns a *NotSingularError when more than one TripRating ID is found.
// Returns a *NotFoundError when no entities are found.
func (trq *TripRatingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = trq.Limit(2).IDs(setContextOp(ctx, trq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{triprating.Label}
	default:
		err = &NotSingularError{triprating.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (trq *TripRatingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := trq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TripRatings.
func (trq *TripRatingQuery) All(ctx context.Context) ([]*TripRating, error) {
	ctx = setContextOp(ctx, trq.ctx, ent.OpQueryAll)
	if err := trq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TripRating, *TripRatingQuery]()
	return withInterceptors[[]*TripRating](ctx, trq, qr, trq.inters)
}

// AllX is like All, but panics if an error occurs.
func (trq *TripRatingQuery) AllX(ctx context.Context) []*TripRating {
	nodes, err := trq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TripRating IDs.
func (trq *TripRatingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if trq.ctx.Unique == nil && trq.path != nil {
		trq.Unique(true)
	}
	ctx = setContextOp(ctx, trq.ctx, ent.OpQueryIDs)
	if err = trq.Select(triprating.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (trq *TripRatingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := trq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (trq *TripRatingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, trq.ctx, ent.OpQueryCount)
	if err := trq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, trq, querierCount[*TripRatingQuery](), trq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (trq *TripRatingQuery) CountX(ctx context.Context) int {
	count, err := trq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (trq *TripRatingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, trq.ctx, ent.OpQueryExist)
	switch _, err := trq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (trq *TripRatingQuery) ExistX(ctx context.Context) bool {
	exist, err := trq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TripRatingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (trq *TripRatingQuery) Clone() *TripRatingQuery {
	if trq == nil {
		return nil
	}
	return &TripRatingQuery{
		config:       trq.config,
		ctx:          trq.ctx.Clone(),
		order:        append([]triprating.OrderOption{}, trq.order...),
		inters:       append([]Interceptor{}, trq.inters...),
		predicates:   append([]predicate.TripRating{}, trq.predicates...),
		withTrip:     trq.withTrip.Clone(),
		withFromUser: trq.withFromUser.Clone(),
		withToUser:   trq.withToUser.Clone(),
		// clone intermediate query.
		sql:  trq.sql.Clone(),
		path: trq.path,
	}
}

// WithTrip tells the query-builder to eager-load the nodes that are connected to
// the "trip" edge. The optional arguments are used to configure the query builder of the edge.
func (trq *TripRatingQuery) WithTrip(opts ...func(*TripQuery)) *TripRatingQuery {
	query := (&TripClient{config: trq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	trq.withTrip = query
	return trq
}

// WithFromUser tells the query-builder to eager-load the nodes that are connected to
// the "from_user" edge. The optional arguments are used to configure the query builder of the edge.
func (trq *TripRatingQuery) WithFromUser(opts ...func(*UserQuery)) *TripRatingQuery {
	query := (&UserClient{config: trq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	trq.withFromUser = query
	return trq
}

// WithToUser tells the query-builder to eager-load the nodes that are connected to
// the "to_user" edge. The optional arguments are used to configure the query builder of the edge.
func (trq *TripRatingQuery) WithToUser(opts ...func(*UserQuery)) *TripRatingQuery {
	query := (&UserClient{config: trq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	trq.withToUser = query
	return trq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TripID uuid.UUID `json:"trip_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TripRating.Query().
//		GroupBy(triprating.FieldTripID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (trq *TripRatingQuery) GroupBy(field string, fields ...string) *TripRatingGroupBy {
	trq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TripRatingGroupBy{build: trq}
	grbuild.flds = &trq.ctx.Fields
	grbuild.label = triprating.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TripID uuid.UUID `json:"trip_id,omitempty"`
//	}
//
//	client.TripRating.Query().
//		Select(triprating.FieldTripID).
//		Scan(ctx, &v)
func (trq *TripRatingQuery) Select(fields ...string) *TripRatingSelect {
	trq.ctx.Fields = append(trq.ctx.Fields, fields...)
	sbuild := &TripRatingSelect{TripRatingQuery: trq}
	sbuild.label = triprating.Label
	sbuild.flds, sbuild.scan = &trq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TripRatingSelect configured with the given aggregations.
func (trq *TripRatingQuery) Aggregate(fns ...AggregateFunc) *TripRatingSelect {
	return trq.Select().Aggregate(fns...)
}

func (trq *TripRatingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range trq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, trq); err != nil {
				return err
			}
		}
	}
	for _, f := range trq.ctx.Fields {
		if !triprating.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if trq.path != nil {
		prev, err := trq.path(ctx)
		if err != nil {
			return err
		}
		trq.sql = prev
	}
	return nil
}

func (trq *TripRatingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TripRating, error) {
	var (
		nodes       = []*TripRating{}
		_spec       = trq.querySpec()
		loadedTypes = [3]bool{
			trq.withTrip != nil,
			trq.withFromUser != nil,
			trq.withToUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TripRating).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TripRating{config: trq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, trq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := trq.withTrip; query != nil {
		if err := trq.loadTrip(ctx, query, nodes, nil,
			func(n *TripRating, e *Trip) { n.Edges.Trip = e }); err != nil {
			return nil, err
		}
	}
	if query := trq.withFromUser; query != nil {
		if err := trq.loadFromUser(ctx, query, nodes, nil,
			func(n *TripRating, e *User) { n.Edges.FromUser = e }); err != nil {
			return nil, err
		}
	}
	if query := trq.withToUser; query != nil {
		if err := trq.loadToUser(ctx, query, nodes, nil,
			func(n *TripRating, e *User) { n.Edges.ToUser = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (trq *TripRatingQuery) loadTrip(ctx context.Context, query *TripQuery, nodes []*TripRating, init func(*TripRating), assign func(*TripRating, *Trip)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TripRating)
	for i := range nodes {
		fk := nodes[i].TripID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(trip.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "trip_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (trq *TripRatingQuery) loadFromUser(ctx context.Context, query *UserQuery, nodes []*TripRating, init func(*TripRating), assign func(*TripRating, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TripRating)
	for i := range nodes {
		fk := nodes[i].FromUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "from_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (trq *TripRatingQuery) loadToUser(ctx context.Context, query *UserQuery, nodes []*TripRating, init func(*TripRating), assign func(*TripRating, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TripRating)
	for i := range nodes {
		fk := nodes[i].ToUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "to_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (trq *TripRatingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := trq.querySpec()
	_spec.Node.Columns = trq.ctx.Fields
	if len(trq.ctx.Fields) > 0 {
		_spec.Unique = trq.ctx.Unique != nil && *trq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, trq.driver, _spec)
}

func (trq *TripRatingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(triprating.Table, triprating.Columns, sqlgraph.NewFieldSpec(triprating.FieldID, field.TypeUUID))
	_spec.From = trq.sql
	if unique := trq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if trq.path != nil {
		_spec.Unique = true
	}
	if fields := trq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, triprating.FieldID)
		for i := range fields {
			if fields[i] != triprating.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if trq.withTrip != nil {
			_spec.Node.AddColumnOnce(triprating.FieldTripID)
		}
		if trq.withFromUser != nil {
			_spec.Node.AddColumnOnce(triprating.FieldFromUserID)
		}
		if trq.withToUser != nil {
			_spec.Node.AddColumnOnce(triprating.FieldToUserID)
		}
	}
	if ps := trq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := trq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := trq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := trq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (trq *TripRatingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(trq.driver.Dialect())
	t1 := builder.Table(triprating.Table)
	columns := trq.ctx.Fields
	if len(columns) == 0 {
		columns = triprating.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if trq.sql != nil {
		selector = trq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if trq.ctx.Unique != nil && *trq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range trq.predicates {
		p(selector)
	}
	for _, p := range trq.order {
		p(selector)
	}
	if offset := trq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := trq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TripRatingGroupBy is the group-by builder for TripRating entities.
type TripRatingGroupBy struct {
	selector
	build *TripRatingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (trgb *TripRatingGroupBy) Aggregate(fns ...AggregateFunc) *TripRatingGroupBy {
	trgb.fns = append(trgb.fns, fns...)
	return trgb
}

// Scan applies the selector query and scans the result into the given value.
func (trgb *TripRatingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, trgb.build.ctx, ent.OpQueryGroupBy)
	if err := trgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TripRatingQuery, *TripRatingGroupBy](ctx, trgb.build, trgb, trgb.build.inters, v)
}

func (trgb *TripRatingGroupBy) sqlScan(ctx context.Context, root *TripRatingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(trgb.fns))
	for _, fn := range trgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*trgb.flds)+len(trgb.fns))
		for _, f := range *trgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*trgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := trgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TripRatingSelect is the builder for selecting fields of TripRating entities.
type TripRatingSelect struct {
	*TripRatingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (trs *TripRatingSelect) Aggregate(fns ...AggregateFunc) *TripRatingSelect {
	trs.fns = append(trs.fns, fns...)
	return trs
}

// Scan applies the selector query and scans the result into the given value.
func (trs *TripRatingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, trs.ctx, ent.OpQuerySelect)
	if err := trs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TripRatingQuery, *TripRatingSelect](ctx, trs.TripRatingQuery, trs, trs.inters, v)
}

func (trs *TripRatingSelect) sqlScan(ctx context.Context, root *TripRatingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(trs.fns))
	for _, fn := range trs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*trs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := trs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
