// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gojeksrepo/ent/predicate"
	"gojeksrepo/ent/triprating"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TripRatingDelete is the builder for deleting a TripRating entity.
type TripRatingDelete struct {
	config
	hooks    []Hook
	mutation *TripRatingMutation
}

// Where appends a list predicates to the TripRatingDelete builder.
func (trd *TripRatingDelete) Where(ps ...predicate.TripRating) *TripRatingDelete {
	trd.mutation.Where(ps...)
	return trd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (trd *TripRatingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, trd.sqlExec, trd.mutation, trd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (trd *TripRatingDelete) ExecX(ctx context.Context) int {
	n, err := trd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (trd *TripRatingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(triprating.Table, sqlgraph.NewFieldSpec(triprating.FieldID, field.TypeUUID))
	if ps := trd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, trd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	trd.mutation.done = true
	return affected, err
}

// TripRatingDeleteOne is the builder for deleting a single TripRating entity.
type TripRatingDeleteOne struct {
	trd *TripRatingDelete
}

// Where appends a list predicates to the TripRatingDelete builder.
func (trdo *TripRatingDeleteOne) Where(ps ...predicate.TripRating) *TripRatingDeleteOne {
	trdo.trd.mutation.Where(ps...)
	return trdo
}

// Exec executes the deletion query.
func (trdo *TripRatingDeleteOne) Exec(ctx context.Context) error {
	n, err := trdo.trd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{triprating.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (trdo *TripRatingDeleteOne) ExecX(ctx context.Context) {
	if err := trdo.Exec(ctx); err != nil {
		panic(err)
	}
}
