// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gojeksrepo/ent/usersadmin"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UsersAdmin is the model entity for the UsersAdmin schema.
type UsersAdmin struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// StatusAdmin holds the value of the "status_admin" field.
	StatusAdmin  int `json:"status_admin,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsersAdmin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersadmin.FieldStatusAdmin:
			values[i] = new(sql.NullInt64)
		case usersadmin.FieldName, usersadmin.FieldUsername, usersadmin.FieldPassword:
			values[i] = new(sql.NullString)
		case usersadmin.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsersAdmin fields.
func (ua *UsersAdmin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersadmin.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ua.ID = *value
			}
		case usersadmin.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ua.Name = value.String
			}
		case usersadmin.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				ua.Username = value.String
			}
		case usersadmin.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				ua.Password = value.String
			}
		case usersadmin.FieldStatusAdmin:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_admin", values[i])
			} else if value.Valid {
				ua.StatusAdmin = int(value.Int64)
			}
		default:
			ua.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsersAdmin.
// This includes values selected through modifiers, order, etc.
func (ua *UsersAdmin) Value(name string) (ent.Value, error) {
	return ua.selectValues.Get(name)
}

// Update returns a builder for updating this UsersAdmin.
// Note that you need to call UsersAdmin.Unwrap() before calling this method if this UsersAdmin
// was returned from a transaction, and the transaction was committed or rolled back.
func (ua *UsersAdmin) Update() *UsersAdminUpdateOne {
	return NewUsersAdminClient(ua.config).UpdateOne(ua)
}

// Unwrap unwraps the UsersAdmin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ua *UsersAdmin) Unwrap() *UsersAdmin {
	_tx, ok := ua.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsersAdmin is not a transactional entity")
	}
	ua.config.driver = _tx.drv
	return ua
}

// String implements the fmt.Stringer.
func (ua *UsersAdmin) String() string {
	var builder strings.Builder
	builder.WriteString("UsersAdmin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ua.ID))
	builder.WriteString("name=")
	builder.WriteString(ua.Name)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(ua.Username)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(ua.Password)
	builder.WriteString(", ")
	builder.WriteString("status_admin=")
	builder.WriteString(fmt.Sprintf("%v", ua.StatusAdmin))
	builder.WriteByte(')')
	return builder.String()
}

// UsersAdmins is a parsable slice of UsersAdmin.
type UsersAdmins []*UsersAdmin
