// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gojeksrepo/ent/predicate"
	"gojeksrepo/ent/usersadmin"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UsersAdminQuery is the builder for querying UsersAdmin entities.
type UsersAdminQuery struct {
	config
	ctx        *QueryContext
	order      []usersadmin.OrderOption
	inters     []Interceptor
	predicates []predicate.UsersAdmin
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UsersAdminQuery builder.
func (uaq *UsersAdminQuery) Where(ps ...predicate.UsersAdmin) *UsersAdminQuery {
	uaq.predicates = append(uaq.predicates, ps...)
	return uaq
}

// Limit the number of records to be returned by this query.
func (uaq *UsersAdminQuery) Limit(limit int) *UsersAdminQuery {
	uaq.ctx.Limit = &limit
	return uaq
}

// Offset to start from.
func (uaq *UsersAdminQuery) Offset(offset int) *UsersAdminQuery {
	uaq.ctx.Offset = &offset
	return uaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uaq *UsersAdminQuery) Unique(unique bool) *UsersAdminQuery {
	uaq.ctx.Unique = &unique
	return uaq
}

// Order specifies how the records should be ordered.
func (uaq *UsersAdminQuery) Order(o ...usersadmin.OrderOption) *UsersAdminQuery {
	uaq.order = append(uaq.order, o...)
	return uaq
}

// First returns the first UsersAdmin entity from the query.
// Returns a *NotFoundError when no UsersAdmin was found.
func (uaq *UsersAdminQuery) First(ctx context.Context) (*UsersAdmin, error) {
	nodes, err := uaq.Limit(1).All(setContextOp(ctx, uaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersadmin.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uaq *UsersAdminQuery) FirstX(ctx context.Context) *UsersAdmin {
	node, err := uaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UsersAdmin ID from the query.
// Returns a *NotFoundError when no UsersAdmin ID was found.
func (uaq *UsersAdminQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = uaq.Limit(1).IDs(setContextOp(ctx, uaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersadmin.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uaq *UsersAdminQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := uaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UsersAdmin entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UsersAdmin entity is found.
// Returns a *NotFoundError when no UsersAdmin entities are found.
func (uaq *UsersAdminQuery) Only(ctx context.Context) (*UsersAdmin, error) {
	nodes, err := uaq.Limit(2).All(setContextOp(ctx, uaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersadmin.Label}
	default:
		return nil, &NotSingularError{usersadmin.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uaq *UsersAdminQuery) OnlyX(ctx context.Context) *UsersAdmin {
	node, err := uaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UsersAdmin ID in the query.
// Returns a *NotSingularError when more than one UsersAdmin ID is found.
// Returns a *NotFoundError when no entities are found.
func (uaq *UsersAdminQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = uaq.Limit(2).IDs(setContextOp(ctx, uaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersadmin.Label}
	default:
		err = &NotSingularError{usersadmin.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uaq *UsersAdminQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := uaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UsersAdmins.
func (uaq *UsersAdminQuery) All(ctx context.Context) ([]*UsersAdmin, error) {
	ctx = setContextOp(ctx, uaq.ctx, ent.OpQueryAll)
	if err := uaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UsersAdmin, *UsersAdminQuery]()
	return withInterceptors[[]*UsersAdmin](ctx, uaq, qr, uaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uaq *UsersAdminQuery) AllX(ctx context.Context) []*UsersAdmin {
	nodes, err := uaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UsersAdmin IDs.
func (uaq *UsersAdminQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if uaq.ctx.Unique == nil && uaq.path != nil {
		uaq.Unique(true)
	}
	ctx = setContextOp(ctx, uaq.ctx, ent.OpQueryIDs)
	if err = uaq.Select(usersadmin.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uaq *UsersAdminQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := uaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uaq *UsersAdminQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uaq.ctx, ent.OpQueryCount)
	if err := uaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uaq, querierCount[*UsersAdminQuery](), uaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uaq *UsersAdminQuery) CountX(ctx context.Context) int {
	count, err := uaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uaq *UsersAdminQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uaq.ctx, ent.OpQueryExist)
	switch _, err := uaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uaq *UsersAdminQuery) ExistX(ctx context.Context) bool {
	exist, err := uaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UsersAdminQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uaq *UsersAdminQuery) Clone() *UsersAdminQuery {
	if uaq == nil {
		return nil
	}
	return &UsersAdminQuery{
		config:     uaq.config,
		ctx:        uaq.ctx.Clone(),
		order:      append([]usersadmin.OrderOption{}, uaq.order...),
		inters:     append([]Interceptor{}, uaq.inters...),
		predicates: append([]predicate.UsersAdmin{}, uaq.predicates...),
		// clone intermediate query.
		sql:  uaq.sql.Clone(),
		path: uaq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UsersAdmin.Query().
//		GroupBy(usersadmin.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uaq *UsersAdminQuery) GroupBy(field string, fields ...string) *UsersAdminGroupBy {
	uaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UsersAdminGroupBy{build: uaq}
	grbuild.flds = &uaq.ctx.Fields
	grbuild.label = usersadmin.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.UsersAdmin.Query().
//		Select(usersadmin.FieldName).
//		Scan(ctx, &v)
func (uaq *UsersAdminQuery) Select(fields ...string) *UsersAdminSelect {
	uaq.ctx.Fields = append(uaq.ctx.Fields, fields...)
	sbuild := &UsersAdminSelect{UsersAdminQuery: uaq}
	sbuild.label = usersadmin.Label
	sbuild.flds, sbuild.scan = &uaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UsersAdminSelect configured with the given aggregations.
func (uaq *UsersAdminQuery) Aggregate(fns ...AggregateFunc) *UsersAdminSelect {
	return uaq.Select().Aggregate(fns...)
}

func (uaq *UsersAdminQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uaq); err != nil {
				return err
			}
		}
	}
	for _, f := range uaq.ctx.Fields {
		if !usersadmin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uaq.path != nil {
		prev, err := uaq.path(ctx)
		if err != nil {
			return err
		}
		uaq.sql = prev
	}
	return nil
}

func (uaq *UsersAdminQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UsersAdmin, error) {
	var (
		nodes = []*UsersAdmin{}
		_spec = uaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UsersAdmin).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UsersAdmin{config: uaq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uaq *UsersAdminQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uaq.querySpec()
	_spec.Node.Columns = uaq.ctx.Fields
	if len(uaq.ctx.Fields) > 0 {
		_spec.Unique = uaq.ctx.Unique != nil && *uaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uaq.driver, _spec)
}

func (uaq *UsersAdminQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usersadmin.Table, usersadmin.Columns, sqlgraph.NewFieldSpec(usersadmin.FieldID, field.TypeUUID))
	_spec.From = uaq.sql
	if unique := uaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uaq.path != nil {
		_spec.Unique = true
	}
	if fields := uaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersadmin.FieldID)
		for i := range fields {
			if fields[i] != usersadmin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uaq *UsersAdminQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uaq.driver.Dialect())
	t1 := builder.Table(usersadmin.Table)
	columns := uaq.ctx.Fields
	if len(columns) == 0 {
		columns = usersadmin.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uaq.sql != nil {
		selector = uaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uaq.ctx.Unique != nil && *uaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uaq.predicates {
		p(selector)
	}
	for _, p := range uaq.order {
		p(selector)
	}
	if offset := uaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UsersAdminGroupBy is the group-by builder for UsersAdmin entities.
type UsersAdminGroupBy struct {
	selector
	build *UsersAdminQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uagb *UsersAdminGroupBy) Aggregate(fns ...AggregateFunc) *UsersAdminGroupBy {
	uagb.fns = append(uagb.fns, fns...)
	return uagb
}

// Scan applies the selector query and scans the result into the given value.
func (uagb *UsersAdminGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uagb.build.ctx, ent.OpQueryGroupBy)
	if err := uagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsersAdminQuery, *UsersAdminGroupBy](ctx, uagb.build, uagb, uagb.build.inters, v)
}

func (uagb *UsersAdminGroupBy) sqlScan(ctx context.Context, root *UsersAdminQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uagb.fns))
	for _, fn := range uagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uagb.flds)+len(uagb.fns))
		for _, f := range *uagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UsersAdminSelect is the builder for selecting fields of UsersAdmin entities.
type UsersAdminSelect struct {
	*UsersAdminQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uas *UsersAdminSelect) Aggregate(fns ...AggregateFunc) *UsersAdminSelect {
	uas.fns = append(uas.fns, fns...)
	return uas
}

// Scan applies the selector query and scans the result into the given value.
func (uas *UsersAdminSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uas.ctx, ent.OpQuerySelect)
	if err := uas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsersAdminQuery, *UsersAdminSelect](ctx, uas.UsersAdminQuery, uas, uas.inters, v)
}

func (uas *UsersAdminSelect) sqlScan(ctx context.Context, root *UsersAdminQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uas.fns))
	for _, fn := range uas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
