// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gojeksrepo/ent/predicate"
	"gojeksrepo/ent/usersadmin"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsersAdminDelete is the builder for deleting a UsersAdmin entity.
type UsersAdminDelete struct {
	config
	hooks    []Hook
	mutation *UsersAdminMutation
}

// Where appends a list predicates to the UsersAdminDelete builder.
func (uad *UsersAdminDelete) Where(ps ...predicate.UsersAdmin) *UsersAdminDelete {
	uad.mutation.Where(ps...)
	return uad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uad *UsersAdminDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uad.sqlExec, uad.mutation, uad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uad *UsersAdminDelete) ExecX(ctx context.Context) int {
	n, err := uad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uad *UsersAdminDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usersadmin.Table, sqlgraph.NewFieldSpec(usersadmin.FieldID, field.TypeUUID))
	if ps := uad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uad.mutation.done = true
	return affected, err
}

// UsersAdminDeleteOne is the builder for deleting a single UsersAdmin entity.
type UsersAdminDeleteOne struct {
	uad *UsersAdminDelete
}

// Where appends a list predicates to the UsersAdminDelete builder.
func (uado *UsersAdminDeleteOne) Where(ps ...predicate.UsersAdmin) *UsersAdminDeleteOne {
	uado.uad.mutation.Where(ps...)
	return uado
}

// Exec executes the deletion query.
func (uado *UsersAdminDeleteOne) Exec(ctx context.Context) error {
	n, err := uado.uad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usersadmin.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uado *UsersAdminDeleteOne) ExecX(ctx context.Context) {
	if err := uado.Exec(ctx); err != nil {
		panic(err)
	}
}
