// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DriverProfile is the predicate function for driverprofile builders.
type DriverProfile func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Trip is the predicate function for trip builders.
type Trip func(*sql.Selector)

// TripRating is the predicate function for triprating builders.
type TripRating func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UsersAdmin is the predicate function for usersadmin builders.
type UsersAdmin func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)
